#build stage
FROM golang:1.21.3-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go

#Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
COPY app.env .
COPY repository/db/migrations ./repository/db/migrations
ENV GRPC_SCHEDULER_ADDRESS=stockinfo-shceduler:9091
ENV DB_SOURCE=postgres://royce:royce@project7-postgres-1:5432/stock_info_distributor?sslmode=disable
EXPOSE 8083
CMD ["/app/main"]