DROP TABLE IF EXISTS  "user_stocks" CASCADE;
DROP TABLE IF EXISTS  "stock_transactions" CASCADE;
DROP TABLE IF EXISTS  "stocks" CASCADE;
DROP TABLE IF EXISTS  "funds" CASCADE;
DROP TABLE IF EXISTS  "users" CASCADE;

