version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=royce
      - POSTGRES_PASSWORD=royce
      - POSTGRES_DB=stock_info
    ports:
      - "5432:5432"
    volumes:
      - ps_data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgres://royce:royce@postgres:5432/stock_info?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  ps_data-volume: