// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.0
// source: rpc_realized_profit_loss.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRealizedProfitLossRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRealizedProfitLossRequest) Reset() {
	*x = GetRealizedProfitLossRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_realized_profit_loss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealizedProfitLossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealizedProfitLossRequest) ProtoMessage() {}

func (x *GetRealizedProfitLossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_realized_profit_loss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealizedProfitLossRequest.ProtoReflect.Descriptor instead.
func (*GetRealizedProfitLossRequest) Descriptor() ([]byte, []int) {
	return file_rpc_realized_profit_loss_proto_rawDescGZIP(), []int{0}
}

type GetRealizedProfitLossResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*RealizedProfitLoss `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetRealizedProfitLossResponse) Reset() {
	*x = GetRealizedProfitLossResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_realized_profit_loss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealizedProfitLossResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealizedProfitLossResponse) ProtoMessage() {}

func (x *GetRealizedProfitLossResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_realized_profit_loss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealizedProfitLossResponse.ProtoReflect.Descriptor instead.
func (*GetRealizedProfitLossResponse) Descriptor() ([]byte, []int) {
	return file_rpc_realized_profit_loss_proto_rawDescGZIP(), []int{1}
}

func (x *GetRealizedProfitLossResponse) GetData() []*RealizedProfitLoss {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUnRealizedProfitLossRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUnRealizedProfitLossRequest) Reset() {
	*x = GetUnRealizedProfitLossRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_realized_profit_loss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnRealizedProfitLossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnRealizedProfitLossRequest) ProtoMessage() {}

func (x *GetUnRealizedProfitLossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_realized_profit_loss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnRealizedProfitLossRequest.ProtoReflect.Descriptor instead.
func (*GetUnRealizedProfitLossRequest) Descriptor() ([]byte, []int) {
	return file_rpc_realized_profit_loss_proto_rawDescGZIP(), []int{2}
}

type GetUnRealizedProfitLossResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*RealizedProfitLoss `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUnRealizedProfitLossResponse) Reset() {
	*x = GetUnRealizedProfitLossResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_realized_profit_loss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnRealizedProfitLossResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnRealizedProfitLossResponse) ProtoMessage() {}

func (x *GetUnRealizedProfitLossResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_realized_profit_loss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnRealizedProfitLossResponse.ProtoReflect.Descriptor instead.
func (*GetUnRealizedProfitLossResponse) Descriptor() ([]byte, []int) {
	return file_rpc_realized_profit_loss_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnRealizedProfitLossResponse) GetData() []*RealizedProfitLoss {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_realized_profit_loss_proto protoreflect.FileDescriptor

var file_rpc_realized_profit_loss_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x74, 0x5f, 0x6c, 0x6f, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x1a, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x74, 0x5f, 0x6c, 0x6f, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x4b, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a,
	0x1e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4d, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x74, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x79,
	0x63, 0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_realized_profit_loss_proto_rawDescOnce sync.Once
	file_rpc_realized_profit_loss_proto_rawDescData = file_rpc_realized_profit_loss_proto_rawDesc
)

func file_rpc_realized_profit_loss_proto_rawDescGZIP() []byte {
	file_rpc_realized_profit_loss_proto_rawDescOnce.Do(func() {
		file_rpc_realized_profit_loss_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_realized_profit_loss_proto_rawDescData)
	})
	return file_rpc_realized_profit_loss_proto_rawDescData
}

var file_rpc_realized_profit_loss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_realized_profit_loss_proto_goTypes = []interface{}{
	(*GetRealizedProfitLossRequest)(nil),    // 0: pb.GetRealizedProfitLossRequest
	(*GetRealizedProfitLossResponse)(nil),   // 1: pb.GetRealizedProfitLossResponse
	(*GetUnRealizedProfitLossRequest)(nil),  // 2: pb.GetUnRealizedProfitLossRequest
	(*GetUnRealizedProfitLossResponse)(nil), // 3: pb.GetUnRealizedProfitLossResponse
	(*RealizedProfitLoss)(nil),              // 4: pb.RealizedProfitLoss
}
var file_rpc_realized_profit_loss_proto_depIdxs = []int32{
	4, // 0: pb.GetRealizedProfitLossResponse.data:type_name -> pb.RealizedProfitLoss
	4, // 1: pb.GetUnRealizedProfitLossResponse.data:type_name -> pb.RealizedProfitLoss
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_realized_profit_loss_proto_init() }
func file_rpc_realized_profit_loss_proto_init() {
	if File_rpc_realized_profit_loss_proto != nil {
		return
	}
	file_realized_profit_loss_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_realized_profit_loss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealizedProfitLossRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_realized_profit_loss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealizedProfitLossResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_realized_profit_loss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnRealizedProfitLossRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_realized_profit_loss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnRealizedProfitLossResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_realized_profit_loss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_realized_profit_loss_proto_goTypes,
		DependencyIndexes: file_rpc_realized_profit_loss_proto_depIdxs,
		MessageInfos:      file_rpc_realized_profit_loss_proto_msgTypes,
	}.Build()
	File_rpc_realized_profit_loss_proto = out.File
	file_rpc_realized_profit_loss_proto_rawDesc = nil
	file_rpc_realized_profit_loss_proto_goTypes = nil
	file_rpc_realized_profit_loss_proto_depIdxs = nil
}
