// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: service_stockinfo_schduler.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_StockInfoSchduler_GetStockDayAvg_0(ctx context.Context, marshaler runtime.Marshaler, client StockInfoSchdulerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StockDayAvgRequest
	var metadata runtime.ServerMetadata

	msg, err := client.GetStockDayAvg(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_StockInfoSchduler_GetStockDayAvg_0(ctx context.Context, marshaler runtime.Marshaler, server StockInfoSchdulerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StockDayAvgRequest
	var metadata runtime.ServerMetadata

	msg, err := server.GetStockDayAvg(ctx, &protoReq)
	return msg, metadata, err

}

func request_StockInfoSchduler_GetStockPriceRealTime_0(ctx context.Context, marshaler runtime.Marshaler, client StockInfoSchdulerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StockPriceRealTimeRequest
	var metadata runtime.ServerMetadata

	msg, err := client.GetStockPriceRealTime(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_StockInfoSchduler_GetStockPriceRealTime_0(ctx context.Context, marshaler runtime.Marshaler, server StockInfoSchdulerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq StockPriceRealTimeRequest
	var metadata runtime.ServerMetadata

	msg, err := server.GetStockPriceRealTime(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterStockInfoSchdulerHandlerServer registers the http handlers for service StockInfoSchduler to "mux".
// UnaryRPC     :call StockInfoSchdulerServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterStockInfoSchdulerHandlerFromEndpoint instead.
func RegisterStockInfoSchdulerHandlerServer(ctx context.Context, mux *runtime.ServeMux, server StockInfoSchdulerServer) error {

	mux.Handle("GET", pattern_StockInfoSchduler_GetStockDayAvg_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.StockInfoSchduler/GetStockDayAvg", runtime.WithHTTPPathPattern("/v1/stock_day_avg"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_StockInfoSchduler_GetStockDayAvg_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StockInfoSchduler_GetStockDayAvg_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_StockInfoSchduler_GetStockPriceRealTime_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.StockInfoSchduler/GetStockPriceRealTime", runtime.WithHTTPPathPattern("/v1/stock_day_real_price/latest"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_StockInfoSchduler_GetStockPriceRealTime_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StockInfoSchduler_GetStockPriceRealTime_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterStockInfoSchdulerHandlerFromEndpoint is same as RegisterStockInfoSchdulerHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterStockInfoSchdulerHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterStockInfoSchdulerHandler(ctx, mux, conn)
}

// RegisterStockInfoSchdulerHandler registers the http handlers for service StockInfoSchduler to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterStockInfoSchdulerHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterStockInfoSchdulerHandlerClient(ctx, mux, NewStockInfoSchdulerClient(conn))
}

// RegisterStockInfoSchdulerHandlerClient registers the http handlers for service StockInfoSchduler
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "StockInfoSchdulerClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "StockInfoSchdulerClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "StockInfoSchdulerClient" to call the correct interceptors.
func RegisterStockInfoSchdulerHandlerClient(ctx context.Context, mux *runtime.ServeMux, client StockInfoSchdulerClient) error {

	mux.Handle("GET", pattern_StockInfoSchduler_GetStockDayAvg_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.StockInfoSchduler/GetStockDayAvg", runtime.WithHTTPPathPattern("/v1/stock_day_avg"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_StockInfoSchduler_GetStockDayAvg_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StockInfoSchduler_GetStockDayAvg_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_StockInfoSchduler_GetStockPriceRealTime_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.StockInfoSchduler/GetStockPriceRealTime", runtime.WithHTTPPathPattern("/v1/stock_day_real_price/latest"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_StockInfoSchduler_GetStockPriceRealTime_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StockInfoSchduler_GetStockPriceRealTime_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_StockInfoSchduler_GetStockDayAvg_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "stock_day_avg"}, ""))

	pattern_StockInfoSchduler_GetStockPriceRealTime_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "stock_day_real_price", "latest"}, ""))
)

var (
	forward_StockInfoSchduler_GetStockDayAvg_0 = runtime.ForwardResponseMessage

	forward_StockInfoSchduler_GetStockPriceRealTime_0 = runtime.ForwardResponseMessage
)
