// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClientRegister struct {
	ClientUid uuid.UUID          `json:"client_uid"`
	StockCode string             `json:"stock_code"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FrontendClient struct {
	ClientUid uuid.UUID          `json:"client_uid"`
	Ip        string             `json:"ip"`
	Region    string             `json:"region"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserRegister struct {
	UserID    int64              `json:"user_id"`
	StockCode string             `json:"stock_code"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
