// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClientRegister(ctx context.Context, arg CreateClientRegisterParams) (ClientRegister, error)
	CreateFrontendClient(ctx context.Context, arg CreateFrontendClientParams) (FrontendClient, error)
	CreateUserRegister(ctx context.Context, arg CreateUserRegisterParams) (UserRegister, error)
	DeleteClientRegister(ctx context.Context, arg DeleteClientRegisterParams) error
	DeleteFrontendClient(ctx context.Context, clientUid uuid.UUID) error
	DeleteUserRegister(ctx context.Context, arg DeleteUserRegisterParams) error
	GetClientRegisterByClientUID(ctx context.Context, clientUid uuid.UUID) ([]ClientRegister, error)
	GetClientRegisters(ctx context.Context, arg GetClientRegistersParams) ([]ClientRegister, error)
	GetFrontendClientByID(ctx context.Context, clientUid uuid.UUID) (FrontendClient, error)
	GetFrontendClientByIP(ctx context.Context, ip string) (FrontendClient, error)
	GetFrontendClients(ctx context.Context, arg GetFrontendClientsParams) ([]FrontendClient, error)
	GetUserRegisterByUserID(ctx context.Context, userID int64) ([]UserRegister, error)
	GetUserRegisters(ctx context.Context, arg GetUserRegistersParams) ([]UserRegister, error)
}

var _ Querier = (*Queries)(nil)
