#build stage
FROM golang:1.21.3-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go

#Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
COPY app.env .
COPY ./doc/fake_source/ ./doc/fake_source/
COPY repository/migrations ./repository/migrations

ENV REDIS_SCHDULER_ADDRESS=scheduler-redis:6379
ENV REDIS_Q_ADDRESS=redis-asynq:6379
EXPOSE 8082
EXPOSE 9091
CMD ["/app/main"]