apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-info-api-depolyment
  labels:
    app: stock-info-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-info-api
  template:
    metadata:
      labels:
        app: stock-info-api
    spec:
      containers:
      - name: stock-info-api
        image: 579275018124.dkr.ecr.ap-northeast-1.amazonaws.com/stockinfo:8bf21d78ff40342c1a6f5e38401b797471842bb7
        ports:
        - containerPort: 8080