apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-info-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "a4991e8375c57441bba31f15f4cc29db-68d1214e64595358.elb.ap-northeast-1.amazonaws.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: broker-api-service
            port:
              number: 8080