apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
#要控制哪個pod
  selector:
    app: zookeeper
  ports:
    - name: http-port
      protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP