apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-info-api-depolyment
  labels:
    app: stock-info-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-info-api
  template:
    metadata:
      labels:
        app: stock-info-api
    spec:
      containers:
      - name: stock-info-api
        image: 579275018124.dkr.ecr.ap-northeast-1.amazonaws.com/stockinfo:latest
        #k8s 永遠抓最新的imgage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080