DROP TABLE IF EXISTS  "user_stock" CASCADE;
DROP TABLE IF EXISTS  "stock_transaction" CASCADE;
DROP TABLE IF EXISTS  "stock" CASCADE;
DROP TABLE IF EXISTS  "fund" CASCADE;
DROP TABLE IF EXISTS  "user" CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp";

