// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.0
// source: rpc_frontend_client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFrontendClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *CreateFrontendClientRequest) Reset() {
	*x = CreateFrontendClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFrontendClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrontendClientRequest) ProtoMessage() {}

func (x *CreateFrontendClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrontendClientRequest.ProtoReflect.Descriptor instead.
func (*CreateFrontendClientRequest) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFrontendClientRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CreateFrontendClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *FrontendClient `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateFrontendClientResponse) Reset() {
	*x = CreateFrontendClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFrontendClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrontendClientResponse) ProtoMessage() {}

func (x *CreateFrontendClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrontendClientResponse.ProtoReflect.Descriptor instead.
func (*CreateFrontendClientResponse) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFrontendClientResponse) GetData() *FrontendClient {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteFrontendClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *DeleteFrontendClientRequest) Reset() {
	*x = DeleteFrontendClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFrontendClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFrontendClientRequest) ProtoMessage() {}

func (x *DeleteFrontendClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFrontendClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteFrontendClientRequest) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFrontendClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DeleteFrontendClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteFrontendClientResponse) Reset() {
	*x = DeleteFrontendClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFrontendClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFrontendClientResponse) ProtoMessage() {}

func (x *DeleteFrontendClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFrontendClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteFrontendClientResponse) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFrontendClientResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetFrontendClientByIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFrontendClientByIPRequest) Reset() {
	*x = GetFrontendClientByIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontendClientByIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendClientByIPRequest) ProtoMessage() {}

func (x *GetFrontendClientByIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendClientByIPRequest.ProtoReflect.Descriptor instead.
func (*GetFrontendClientByIPRequest) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{4}
}

type GetFrontendClientByIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *FrontendClient `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFrontendClientByIPResponse) Reset() {
	*x = GetFrontendClientByIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_frontend_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontendClientByIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendClientByIPResponse) ProtoMessage() {}

func (x *GetFrontendClientByIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_frontend_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendClientByIPResponse.ProtoReflect.Descriptor instead.
func (*GetFrontendClientByIPResponse) Descriptor() ([]byte, []int) {
	return file_rpc_frontend_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetFrontendClientByIPResponse) GetData() *FrontendClient {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_frontend_client_proto protoreflect.FileDescriptor

var file_rpc_frontend_client_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x15, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a,
	0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x36, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x52, 0x6f, 0x79, 0x63, 0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_frontend_client_proto_rawDescOnce sync.Once
	file_rpc_frontend_client_proto_rawDescData = file_rpc_frontend_client_proto_rawDesc
)

func file_rpc_frontend_client_proto_rawDescGZIP() []byte {
	file_rpc_frontend_client_proto_rawDescOnce.Do(func() {
		file_rpc_frontend_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_frontend_client_proto_rawDescData)
	})
	return file_rpc_frontend_client_proto_rawDescData
}

var file_rpc_frontend_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_frontend_client_proto_goTypes = []interface{}{
	(*CreateFrontendClientRequest)(nil),   // 0: pb.CreateFrontendClientRequest
	(*CreateFrontendClientResponse)(nil),  // 1: pb.CreateFrontendClientResponse
	(*DeleteFrontendClientRequest)(nil),   // 2: pb.DeleteFrontendClientRequest
	(*DeleteFrontendClientResponse)(nil),  // 3: pb.DeleteFrontendClientResponse
	(*GetFrontendClientByIPRequest)(nil),  // 4: pb.GetFrontendClientByIPRequest
	(*GetFrontendClientByIPResponse)(nil), // 5: pb.GetFrontendClientByIPResponse
	(*FrontendClient)(nil),                // 6: pb.FrontendClient
}
var file_rpc_frontend_client_proto_depIdxs = []int32{
	6, // 0: pb.CreateFrontendClientResponse.data:type_name -> pb.FrontendClient
	6, // 1: pb.GetFrontendClientByIPResponse.data:type_name -> pb.FrontendClient
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_frontend_client_proto_init() }
func file_rpc_frontend_client_proto_init() {
	if File_rpc_frontend_client_proto != nil {
		return
	}
	file_frontend_client_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_frontend_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFrontendClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_frontend_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFrontendClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_frontend_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFrontendClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_frontend_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFrontendClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_frontend_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontendClientByIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_frontend_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontendClientByIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_frontend_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_frontend_client_proto_goTypes,
		DependencyIndexes: file_rpc_frontend_client_proto_depIdxs,
		MessageInfos:      file_rpc_frontend_client_proto_msgTypes,
	}.Build()
	File_rpc_frontend_client_proto = out.File
	file_rpc_frontend_client_proto_rawDesc = nil
	file_rpc_frontend_client_proto_goTypes = nil
	file_rpc_frontend_client_proto_depIdxs = nil
}
