// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.0
// source: stock_transation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockTransation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransationId        int64  `protobuf:"varint,1,opt,name=transation_id,json=transationId,proto3" json:"transation_id,omitempty"`
	UserId              int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StockId             int64  `protobuf:"varint,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	TransationType      string `protobuf:"bytes,4,opt,name=transation_type,json=transationType,proto3" json:"transation_type,omitempty"`
	TransAmt            int64  `protobuf:"varint,5,opt,name=trans_amt,json=transAmt,proto3" json:"trans_amt,omitempty"`
	TransPricesPerShare string `protobuf:"bytes,6,opt,name=trans_prices_per_share,json=transPricesPerShare,proto3" json:"trans_prices_per_share,omitempty"`
	Result              string `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Msg                 string `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StockTransation) Reset() {
	*x = StockTransation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_transation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockTransation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTransation) ProtoMessage() {}

func (x *StockTransation) ProtoReflect() protoreflect.Message {
	mi := &file_stock_transation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTransation.ProtoReflect.Descriptor instead.
func (*StockTransation) Descriptor() ([]byte, []int) {
	return file_stock_transation_proto_rawDescGZIP(), []int{0}
}

func (x *StockTransation) GetTransationId() int64 {
	if x != nil {
		return x.TransationId
	}
	return 0
}

func (x *StockTransation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StockTransation) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *StockTransation) GetTransationType() string {
	if x != nil {
		return x.TransationType
	}
	return ""
}

func (x *StockTransation) GetTransAmt() int64 {
	if x != nil {
		return x.TransAmt
	}
	return 0
}

func (x *StockTransation) GetTransPricesPerShare() string {
	if x != nil {
		return x.TransPricesPerShare
	}
	return ""
}

func (x *StockTransation) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StockTransation) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_stock_transation_proto protoreflect.FileDescriptor

var file_stock_transation_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x8f, 0x02, 0x0a,
	0x0f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x61, 0x6d, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x41, 0x6d, 0x74, 0x12,
	0x33, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x50, 0x65, 0x72, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x35,
	0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x79,
	0x63, 0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x66, 0x6f, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_transation_proto_rawDescOnce sync.Once
	file_stock_transation_proto_rawDescData = file_stock_transation_proto_rawDesc
)

func file_stock_transation_proto_rawDescGZIP() []byte {
	file_stock_transation_proto_rawDescOnce.Do(func() {
		file_stock_transation_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_transation_proto_rawDescData)
	})
	return file_stock_transation_proto_rawDescData
}

var file_stock_transation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stock_transation_proto_goTypes = []interface{}{
	(*StockTransation)(nil), // 0: pb.StockTransation
}
var file_stock_transation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_transation_proto_init() }
func file_stock_transation_proto_init() {
	if File_stock_transation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_transation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockTransation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_transation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_transation_proto_goTypes,
		DependencyIndexes: file_stock_transation_proto_depIdxs,
		MessageInfos:      file_stock_transation_proto_msgTypes,
	}.Build()
	File_stock_transation_proto = out.File
	file_stock_transation_proto_rawDesc = nil
	file_stock_transation_proto_goTypes = nil
	file_stock_transation_proto_depIdxs = nil
}
