// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"database/sql"
	"time"
)

type StockDayAvgAll struct {
	ID              int64          `json:"id"`
	Code            string         `json:"code"`
	StockName       string         `json:"stock_name"`
	ClosePrice      string         `json:"close_price"`
	MonthlyAvgPrice string         `json:"monthly_avg_price"`
	CrDate          time.Time      `json:"cr_date"`
	UpDate          sql.NullTime   `json:"up_date"`
	CrUser          string         `json:"cr_user"`
	UpUser          sql.NullString `json:"up_user"`
}
