// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type StockDayAvgAll struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	StockName       string             `json:"stock_name"`
	ClosePrice      pgtype.Numeric     `json:"close_price"`
	MonthlyAvgPrice pgtype.Numeric     `json:"monthly_avg_price"`
	CrDate          time.Time          `json:"cr_date"`
	UpDate          pgtype.Timestamptz `json:"up_date"`
	CrUser          string             `json:"cr_user"`
	UpUser          pgtype.Text        `json:"up_user"`
}

type StockPriceRealtime struct {
	Code         string         `json:"code"`
	StockName    string         `json:"stock_name"`
	TradeVolume  pgtype.Numeric `json:"trade_volume"`
	TradeValue   pgtype.Numeric `json:"trade_value"`
	OpeningPrice pgtype.Numeric `json:"opening_price"`
	HighestPrice pgtype.Numeric `json:"highest_price"`
	LowestPrice  pgtype.Numeric `json:"lowest_price"`
	ClosingPrice pgtype.Numeric `json:"closing_price"`
	Change       pgtype.Numeric `json:"change"`
	Transaction  pgtype.Numeric `json:"transaction"`
	TransTime    time.Time      `json:"trans_time"`
}
