// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: stock_day_avg_all.sql

package repository

import (
	"context"

	"github.com/lib/pq"
)

const batchDeleteSDAVGALL = `-- name: BatchDeleteSDAVGALL :exec
DELETE FROM "stock_day_avg_all"
WHERE  id = ANY($1::bigint[])
`

func (q *Queries) BatchDeleteSDAVGALL(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.ExecContext(ctx, batchDeleteSDAVGALL, pq.Array(dollar_1))
	return err
}

const createSDAVGALL = `-- name: CreateSDAVGALL :one
INSERT INTO "stock_day_avg_all" (
    code,
    stock_name,
    close_price,
    monthly_avg_price
) VALUES(
    $1, $2, $3, $4
) RETURNING id, code, stock_name, close_price, monthly_avg_price, cr_date, up_date, cr_user, up_user
`

type CreateSDAVGALLParams struct {
	Code            string `json:"code"`
	StockName       string `json:"stock_name"`
	ClosePrice      string `json:"close_price"`
	MonthlyAvgPrice string `json:"monthly_avg_price"`
}

func (q *Queries) CreateSDAVGALL(ctx context.Context, arg CreateSDAVGALLParams) (StockDayAvgAll, error) {
	row := q.db.QueryRowContext(ctx, createSDAVGALL,
		arg.Code,
		arg.StockName,
		arg.ClosePrice,
		arg.MonthlyAvgPrice,
	)
	var i StockDayAvgAll
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StockName,
		&i.ClosePrice,
		&i.MonthlyAvgPrice,
		&i.CrDate,
		&i.UpDate,
		&i.CrUser,
		&i.UpUser,
	)
	return i, err
}

const getSDAVGALLs = `-- name: GetSDAVGALLs :many
SELECT id, code, stock_name, close_price, monthly_avg_price, cr_date, up_date, cr_user, up_user FROM "stock_day_avg_all"
ORDER BY code
LIMIT $1
OFFSET $2
`

type GetSDAVGALLsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSDAVGALLs(ctx context.Context, arg GetSDAVGALLsParams) ([]StockDayAvgAll, error) {
	rows, err := q.db.QueryContext(ctx, getSDAVGALLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockDayAvgAll{}
	for rows.Next() {
		var i StockDayAvgAll
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.StockName,
			&i.ClosePrice,
			&i.MonthlyAvgPrice,
			&i.CrDate,
			&i.UpDate,
			&i.CrUser,
			&i.UpUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
