// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateStockTransaction(ctx context.Context, arg CreateStockTransactionParams) (StockTransaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserStock(ctx context.Context, arg CreateUserStockParams) (UserStock, error)
	DeleteFund(ctx context.Context, fundID int64) error
	DeleteStock(ctx context.Context, stockID int64) error
	DeleteStockTransaction(ctx context.Context, transationid int64) error
	DeleteUser(ctx context.Context, userID int64) error
	DeleteUserStock(ctx context.Context, userStockID int64) error
	GetFund(ctx context.Context, fundID int64) (Fund, error)
	GetStock(ctx context.Context, stockID int64) (Stock, error)
	GetStockTransaction(ctx context.Context, transationid int64) (StockTransaction, error)
	GetStockTransactions(ctx context.Context, arg GetStockTransactionsParams) ([]StockTransaction, error)
	GetStockTransactionsByDate(ctx context.Context, arg GetStockTransactionsByDateParams) ([]StockTransaction, error)
	GetStockTransactionsByStockId(ctx context.Context, arg GetStockTransactionsByStockIdParams) ([]StockTransaction, error)
	GetStockTransactionsByUserId(ctx context.Context, arg GetStockTransactionsByUserIdParams) ([]StockTransaction, error)
	GetUser(ctx context.Context, userID int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserForUpdateNoKey(ctx context.Context, userID int64) (User, error)
	GetUserStock(ctx context.Context, userStockID int64) (UserStock, error)
	GetUserStocks(ctx context.Context, arg GetUserStocksParams) ([]UserStock, error)
	GetUserStocksByPDate(ctx context.Context, arg GetUserStocksByPDateParams) ([]UserStock, error)
	GetUserStocksByStockId(ctx context.Context, arg GetUserStocksByStockIdParams) ([]UserStock, error)
	GetUserStocksByUserAStock(ctx context.Context, arg GetUserStocksByUserAStockParams) ([]UserStock, error)
	GetUserStocksByUserId(ctx context.Context, arg GetUserStocksByUserIdParams) ([]UserStock, error)
	GetfundByUidandFid(ctx context.Context, arg GetfundByUidandFidParams) (Fund, error)
	GetfundByUidandFidForUpdateNoK(ctx context.Context, arg GetfundByUidandFidForUpdateNoKParams) (Fund, error)
	GetfundByUserId(ctx context.Context, arg GetfundByUserIdParams) ([]Fund, error)
	Getfunds(ctx context.Context, arg GetfundsParams) ([]Fund, error)
	GetserStockByUidandSid(ctx context.Context, arg GetserStockByUidandSidParams) (UserStock, error)
	GetserStockByUidandSidForUpdateNoK(ctx context.Context, arg GetserStockByUidandSidForUpdateNoKParams) (UserStock, error)
	GetstockByCN(ctx context.Context, arg GetstockByCNParams) ([]Stock, error)
	GetstockByTS(ctx context.Context, arg GetstockByTSParams) ([]Stock, error)
	Getstocks(ctx context.Context, arg GetstocksParams) ([]Stock, error)
	Getusers(ctx context.Context, arg GetusersParams) ([]User, error)
	UpdateFund(ctx context.Context, arg UpdateFundParams) (Fund, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStock(ctx context.Context, arg UpdateUserStockParams) (UserStock, error)
}

var _ Querier = (*Queries)(nil)
