#build stage
FROM golang:1.21.3-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go

#Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
COPY app.env .
ENV GRPC_SCHEDULER_ADDRESS=shceduler:9092
ENV GRPC_STOCKINFO_ADDRESS=stockinfo:9091
ENV GRPC_DISTRIBUTOR_ADDRESS=distributor:9093
ENV REDIS_Q_ADDRESS=redis-asynq:6379
ENV SERVICEID=broker
EXPOSE 8080
CMD ["/app/main"]