// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RoyceAzure/go-stockinfo/repository/db/sqlc (interfaces: Store)

// Package mock_sqlc is a generated GoMock package.
package mock_sqlc

import (
	context "context"
	reflect "reflect"

	db "github.com/RoyceAzure/go-stockinfo/repository/db/sqlc"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateFund mocks base method.
func (m *MockStore) CreateFund(arg0 context.Context, arg1 db.CreateFundParams) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFund", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFund indicates an expected call of CreateFund.
func (mr *MockStoreMockRecorder) CreateFund(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFund", reflect.TypeOf((*MockStore)(nil).CreateFund), arg0, arg1)
}

// CreateRealizedProfitLoss mocks base method.
func (m *MockStore) CreateRealizedProfitLoss(arg0 context.Context, arg1 db.CreateRealizedProfitLossParams) (db.RealizedProfitLoss, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRealizedProfitLoss", arg0, arg1)
	ret0, _ := ret[0].(db.RealizedProfitLoss)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRealizedProfitLoss indicates an expected call of CreateRealizedProfitLoss.
func (mr *MockStoreMockRecorder) CreateRealizedProfitLoss(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRealizedProfitLoss", reflect.TypeOf((*MockStore)(nil).CreateRealizedProfitLoss), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateStock mocks base method.
func (m *MockStore) CreateStock(arg0 context.Context, arg1 db.CreateStockParams) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStock", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStock indicates an expected call of CreateStock.
func (mr *MockStoreMockRecorder) CreateStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStock", reflect.TypeOf((*MockStore)(nil).CreateStock), arg0, arg1)
}

// CreateStockTransaction mocks base method.
func (m *MockStore) CreateStockTransaction(arg0 context.Context, arg1 db.CreateStockTransactionParams) (db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStockTransaction indicates an expected call of CreateStockTransaction.
func (mr *MockStoreMockRecorder) CreateStockTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockTransaction", reflect.TypeOf((*MockStore)(nil).CreateStockTransaction), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserStock mocks base method.
func (m *MockStore) CreateUserStock(arg0 context.Context, arg1 db.CreateUserStockParams) (db.UserStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserStock", arg0, arg1)
	ret0, _ := ret[0].(db.UserStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserStock indicates an expected call of CreateUserStock.
func (mr *MockStoreMockRecorder) CreateUserStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserStock", reflect.TypeOf((*MockStore)(nil).CreateUserStock), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(arg0 context.Context, arg1 db.CreateUserTxParams) (db.CreateUserTxResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserTxResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), arg0, arg1)
}

// CreateVerifyEmail mocks base method.
func (m *MockStore) CreateVerifyEmail(arg0 context.Context, arg1 db.CreateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockStoreMockRecorder) CreateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockStore)(nil).CreateVerifyEmail), arg0, arg1)
}

// DeleteFund mocks base method.
func (m *MockStore) DeleteFund(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFund", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFund indicates an expected call of DeleteFund.
func (mr *MockStoreMockRecorder) DeleteFund(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFund", reflect.TypeOf((*MockStore)(nil).DeleteFund), arg0, arg1)
}

// DeleteStock mocks base method.
func (m *MockStore) DeleteStock(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStock", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStock indicates an expected call of DeleteStock.
func (mr *MockStoreMockRecorder) DeleteStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStock", reflect.TypeOf((*MockStore)(nil).DeleteStock), arg0, arg1)
}

// DeleteStockTransaction mocks base method.
func (m *MockStore) DeleteStockTransaction(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStockTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStockTransaction indicates an expected call of DeleteStockTransaction.
func (mr *MockStoreMockRecorder) DeleteStockTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStockTransaction", reflect.TypeOf((*MockStore)(nil).DeleteStockTransaction), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserStock mocks base method.
func (m *MockStore) DeleteUserStock(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserStock", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserStock indicates an expected call of DeleteUserStock.
func (mr *MockStoreMockRecorder) DeleteUserStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserStock", reflect.TypeOf((*MockStore)(nil).DeleteUserStock), arg0, arg1)
}

// GetFund mocks base method.
func (m *MockStore) GetFund(arg0 context.Context, arg1 int64) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFund", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFund indicates an expected call of GetFund.
func (mr *MockStoreMockRecorder) GetFund(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFund", reflect.TypeOf((*MockStore)(nil).GetFund), arg0, arg1)
}

// GetFundByUidandCurForUpdateNoK mocks base method.
func (m *MockStore) GetFundByUidandCurForUpdateNoK(arg0 context.Context, arg1 db.GetFundByUidandCurForUpdateNoKParams) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundByUidandCurForUpdateNoK", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundByUidandCurForUpdateNoK indicates an expected call of GetFundByUidandCurForUpdateNoK.
func (mr *MockStoreMockRecorder) GetFundByUidandCurForUpdateNoK(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundByUidandCurForUpdateNoK", reflect.TypeOf((*MockStore)(nil).GetFundByUidandCurForUpdateNoK), arg0, arg1)
}

// GetFundByUidandFid mocks base method.
func (m *MockStore) GetFundByUidandFid(arg0 context.Context, arg1 db.GetFundByUidandFidParams) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundByUidandFid", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundByUidandFid indicates an expected call of GetFundByUidandFid.
func (mr *MockStoreMockRecorder) GetFundByUidandFid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundByUidandFid", reflect.TypeOf((*MockStore)(nil).GetFundByUidandFid), arg0, arg1)
}

// GetFundByUidandFidForUpdateNoK mocks base method.
func (m *MockStore) GetFundByUidandFidForUpdateNoK(arg0 context.Context, arg1 db.GetFundByUidandFidForUpdateNoKParams) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundByUidandFidForUpdateNoK", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundByUidandFidForUpdateNoK indicates an expected call of GetFundByUidandFidForUpdateNoK.
func (mr *MockStoreMockRecorder) GetFundByUidandFidForUpdateNoK(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundByUidandFidForUpdateNoK", reflect.TypeOf((*MockStore)(nil).GetFundByUidandFidForUpdateNoK), arg0, arg1)
}

// GetFundByUserId mocks base method.
func (m *MockStore) GetFundByUserId(arg0 context.Context, arg1 db.GetFundByUserIdParams) ([]db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFundByUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFundByUserId indicates an expected call of GetFundByUserId.
func (mr *MockStoreMockRecorder) GetFundByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFundByUserId", reflect.TypeOf((*MockStore)(nil).GetFundByUserId), arg0, arg1)
}

// GetFunds mocks base method.
func (m *MockStore) GetFunds(arg0 context.Context, arg1 db.GetFundsParams) ([]db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunds", arg0, arg1)
	ret0, _ := ret[0].([]db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunds indicates an expected call of GetFunds.
func (mr *MockStoreMockRecorder) GetFunds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunds", reflect.TypeOf((*MockStore)(nil).GetFunds), arg0, arg1)
}

// GetRealizedProfitLoss mocks base method.
func (m *MockStore) GetRealizedProfitLoss(arg0 context.Context, arg1 int64) (db.RealizedProfitLoss, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealizedProfitLoss", arg0, arg1)
	ret0, _ := ret[0].(db.RealizedProfitLoss)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealizedProfitLoss indicates an expected call of GetRealizedProfitLoss.
func (mr *MockStoreMockRecorder) GetRealizedProfitLoss(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealizedProfitLoss", reflect.TypeOf((*MockStore)(nil).GetRealizedProfitLoss), arg0, arg1)
}

// GetRealizedProfitLosssByUserId mocks base method.
func (m *MockStore) GetRealizedProfitLosssByUserId(arg0 context.Context, arg1 db.GetRealizedProfitLosssByUserIdParams) ([]db.RealizedProfitLoss, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealizedProfitLosssByUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.RealizedProfitLoss)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealizedProfitLosssByUserId indicates an expected call of GetRealizedProfitLosssByUserId.
func (mr *MockStoreMockRecorder) GetRealizedProfitLosssByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealizedProfitLosssByUserId", reflect.TypeOf((*MockStore)(nil).GetRealizedProfitLosssByUserId), arg0, arg1)
}

// GetRealizedProfitLosssByUserIdDetial mocks base method.
func (m *MockStore) GetRealizedProfitLosssByUserIdDetial(arg0 context.Context, arg1 db.GetRealizedProfitLosssByUserIdDetialParams) ([]db.GetRealizedProfitLosssByUserIdDetialRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealizedProfitLosssByUserIdDetial", arg0, arg1)
	ret0, _ := ret[0].([]db.GetRealizedProfitLosssByUserIdDetialRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealizedProfitLosssByUserIdDetial indicates an expected call of GetRealizedProfitLosssByUserIdDetial.
func (mr *MockStoreMockRecorder) GetRealizedProfitLosssByUserIdDetial(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealizedProfitLosssByUserIdDetial", reflect.TypeOf((*MockStore)(nil).GetRealizedProfitLosssByUserIdDetial), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetStock mocks base method.
func (m *MockStore) GetStock(arg0 context.Context, arg1 int64) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStock", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockStoreMockRecorder) GetStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockStore)(nil).GetStock), arg0, arg1)
}

// GetStockByCN mocks base method.
func (m *MockStore) GetStockByCN(arg0 context.Context, arg1 string) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByCN", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByCN indicates an expected call of GetStockByCN.
func (mr *MockStoreMockRecorder) GetStockByCN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByCN", reflect.TypeOf((*MockStore)(nil).GetStockByCN), arg0, arg1)
}

// GetStockByCode mocks base method.
func (m *MockStore) GetStockByCode(arg0 context.Context, arg1 string) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByCode", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByCode indicates an expected call of GetStockByCode.
func (mr *MockStoreMockRecorder) GetStockByCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByCode", reflect.TypeOf((*MockStore)(nil).GetStockByCode), arg0, arg1)
}

// GetStockForUpdate mocks base method.
func (m *MockStore) GetStockForUpdate(arg0 context.Context, arg1 int64) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockForUpdate", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockForUpdate indicates an expected call of GetStockForUpdate.
func (mr *MockStoreMockRecorder) GetStockForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockForUpdate", reflect.TypeOf((*MockStore)(nil).GetStockForUpdate), arg0, arg1)
}

// GetStockTransaction mocks base method.
func (m *MockStore) GetStockTransaction(arg0 context.Context, arg1 int64) (db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransaction indicates an expected call of GetStockTransaction.
func (mr *MockStoreMockRecorder) GetStockTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransaction", reflect.TypeOf((*MockStore)(nil).GetStockTransaction), arg0, arg1)
}

// GetStockTransactionsByDate mocks base method.
func (m *MockStore) GetStockTransactionsByDate(arg0 context.Context, arg1 db.GetStockTransactionsByDateParams) ([]db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransactionsByDate", arg0, arg1)
	ret0, _ := ret[0].([]db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransactionsByDate indicates an expected call of GetStockTransactionsByDate.
func (mr *MockStoreMockRecorder) GetStockTransactionsByDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransactionsByDate", reflect.TypeOf((*MockStore)(nil).GetStockTransactionsByDate), arg0, arg1)
}

// GetStockTransactionsByStockId mocks base method.
func (m *MockStore) GetStockTransactionsByStockId(arg0 context.Context, arg1 db.GetStockTransactionsByStockIdParams) ([]db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransactionsByStockId", arg0, arg1)
	ret0, _ := ret[0].([]db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransactionsByStockId indicates an expected call of GetStockTransactionsByStockId.
func (mr *MockStoreMockRecorder) GetStockTransactionsByStockId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransactionsByStockId", reflect.TypeOf((*MockStore)(nil).GetStockTransactionsByStockId), arg0, arg1)
}

// GetStockTransactionsByUserId mocks base method.
func (m *MockStore) GetStockTransactionsByUserId(arg0 context.Context, arg1 db.GetStockTransactionsByUserIdParams) ([]db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransactionsByUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransactionsByUserId indicates an expected call of GetStockTransactionsByUserId.
func (mr *MockStoreMockRecorder) GetStockTransactionsByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransactionsByUserId", reflect.TypeOf((*MockStore)(nil).GetStockTransactionsByUserId), arg0, arg1)
}

// GetStockTransactionsFilter mocks base method.
func (m *MockStore) GetStockTransactionsFilter(arg0 context.Context, arg1 db.GetStockTransactionsFilterParams) ([]db.GetStockTransactionsFilterRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockTransactionsFilter", arg0, arg1)
	ret0, _ := ret[0].([]db.GetStockTransactionsFilterRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockTransactionsFilter indicates an expected call of GetStockTransactionsFilter.
func (mr *MockStoreMockRecorder) GetStockTransactionsFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockTransactionsFilter", reflect.TypeOf((*MockStore)(nil).GetStockTransactionsFilter), arg0, arg1)
}

// GetStocks mocks base method.
func (m *MockStore) GetStocks(arg0 context.Context, arg1 db.GetStocksParams) ([]db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocks", arg0, arg1)
	ret0, _ := ret[0].([]db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocks indicates an expected call of GetStocks.
func (mr *MockStoreMockRecorder) GetStocks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocks", reflect.TypeOf((*MockStore)(nil).GetStocks), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserForUpdateNoKey mocks base method.
func (m *MockStore) GetUserForUpdateNoKey(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdateNoKey", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdateNoKey indicates an expected call of GetUserForUpdateNoKey.
func (mr *MockStoreMockRecorder) GetUserForUpdateNoKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdateNoKey", reflect.TypeOf((*MockStore)(nil).GetUserForUpdateNoKey), arg0, arg1)
}

// GetUserStock mocks base method.
func (m *MockStore) GetUserStock(arg0 context.Context, arg1 int64) (db.UserStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStock", arg0, arg1)
	ret0, _ := ret[0].(db.UserStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStock indicates an expected call of GetUserStock.
func (mr *MockStoreMockRecorder) GetUserStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStock", reflect.TypeOf((*MockStore)(nil).GetUserStock), arg0, arg1)
}

// GetUserStockByUidandSidForUpdateNoK mocks base method.
func (m *MockStore) GetUserStockByUidandSidForUpdateNoK(arg0 context.Context, arg1 db.GetUserStockByUidandSidForUpdateNoKParams) (db.UserStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStockByUidandSidForUpdateNoK", arg0, arg1)
	ret0, _ := ret[0].(db.UserStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStockByUidandSidForUpdateNoK indicates an expected call of GetUserStockByUidandSidForUpdateNoK.
func (mr *MockStoreMockRecorder) GetUserStockByUidandSidForUpdateNoK(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStockByUidandSidForUpdateNoK", reflect.TypeOf((*MockStore)(nil).GetUserStockByUidandSidForUpdateNoK), arg0, arg1)
}

// GetUserStocksByUserId mocks base method.
func (m *MockStore) GetUserStocksByUserId(arg0 context.Context, arg1 db.GetUserStocksByUserIdParams) ([]db.GetUserStocksByUserIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStocksByUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.GetUserStocksByUserIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStocksByUserId indicates an expected call of GetUserStocksByUserId.
func (mr *MockStoreMockRecorder) GetUserStocksByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStocksByUserId", reflect.TypeOf((*MockStore)(nil).GetUserStocksByUserId), arg0, arg1)
}

// GetserStockByUidandSid mocks base method.
func (m *MockStore) GetserStockByUidandSid(arg0 context.Context, arg1 db.GetserStockByUidandSidParams) (db.UserStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetserStockByUidandSid", arg0, arg1)
	ret0, _ := ret[0].(db.UserStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetserStockByUidandSid indicates an expected call of GetserStockByUidandSid.
func (mr *MockStoreMockRecorder) GetserStockByUidandSid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetserStockByUidandSid", reflect.TypeOf((*MockStore)(nil).GetserStockByUidandSid), arg0, arg1)
}

// GetstockByTS mocks base method.
func (m *MockStore) GetstockByTS(arg0 context.Context, arg1 db.GetstockByTSParams) ([]db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetstockByTS", arg0, arg1)
	ret0, _ := ret[0].([]db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetstockByTS indicates an expected call of GetstockByTS.
func (mr *MockStoreMockRecorder) GetstockByTS(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetstockByTS", reflect.TypeOf((*MockStore)(nil).GetstockByTS), arg0, arg1)
}

// Getusers mocks base method.
func (m *MockStore) Getusers(arg0 context.Context, arg1 db.GetusersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getusers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Getusers indicates an expected call of Getusers.
func (mr *MockStoreMockRecorder) Getusers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getusers", reflect.TypeOf((*MockStore)(nil).Getusers), arg0, arg1)
}

// TransferStockTx mocks base method.
func (m *MockStore) TransferStockTx(arg0 context.Context, arg1 db.TransferStockTxParams) (db.TransferStockTxResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferStockTx", arg0, arg1)
	ret0, _ := ret[0].(db.TransferStockTxResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferStockTx indicates an expected call of TransferStockTx.
func (mr *MockStoreMockRecorder) TransferStockTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferStockTx", reflect.TypeOf((*MockStore)(nil).TransferStockTx), arg0, arg1)
}

// TruncateStocks mocks base method.
func (m *MockStore) TruncateStocks(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateStocks", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TruncateStocks indicates an expected call of TruncateStocks.
func (mr *MockStoreMockRecorder) TruncateStocks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateStocks", reflect.TypeOf((*MockStore)(nil).TruncateStocks), arg0)
}

// UpdateFund mocks base method.
func (m *MockStore) UpdateFund(arg0 context.Context, arg1 db.UpdateFundParams) (db.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFund", arg0, arg1)
	ret0, _ := ret[0].(db.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFund indicates an expected call of UpdateFund.
func (mr *MockStoreMockRecorder) UpdateFund(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFund", reflect.TypeOf((*MockStore)(nil).UpdateFund), arg0, arg1)
}

// UpdateFundTx mocks base method.
func (m *MockStore) UpdateFundTx(arg0 context.Context, arg1 db.UpdateFundTxParams) (db.UpdateFundTxResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFundTx", arg0, arg1)
	ret0, _ := ret[0].(db.UpdateFundTxResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFundTx indicates an expected call of UpdateFundTx.
func (mr *MockStoreMockRecorder) UpdateFundTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFundTx", reflect.TypeOf((*MockStore)(nil).UpdateFundTx), arg0, arg1)
}

// UpdateStock mocks base method.
func (m *MockStore) UpdateStock(arg0 context.Context, arg1 db.UpdateStockParams) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStock", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStock indicates an expected call of UpdateStock.
func (mr *MockStoreMockRecorder) UpdateStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStock", reflect.TypeOf((*MockStore)(nil).UpdateStock), arg0, arg1)
}

// UpdateStockCPByCode mocks base method.
func (m *MockStore) UpdateStockCPByCode(arg0 context.Context, arg1 db.UpdateStockCPByCodeParams) (db.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockCPByCode", arg0, arg1)
	ret0, _ := ret[0].(db.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStockCPByCode indicates an expected call of UpdateStockCPByCode.
func (mr *MockStoreMockRecorder) UpdateStockCPByCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockCPByCode", reflect.TypeOf((*MockStore)(nil).UpdateStockCPByCode), arg0, arg1)
}

// UpdateStockTransationResult mocks base method.
func (m *MockStore) UpdateStockTransationResult(arg0 context.Context, arg1 db.UpdateStockTransationResultParams) (db.StockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockTransationResult", arg0, arg1)
	ret0, _ := ret[0].(db.StockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStockTransationResult indicates an expected call of UpdateStockTransationResult.
func (mr *MockStoreMockRecorder) UpdateStockTransationResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockTransationResult", reflect.TypeOf((*MockStore)(nil).UpdateStockTransationResult), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserStock mocks base method.
func (m *MockStore) UpdateUserStock(arg0 context.Context, arg1 db.UpdateUserStockParams) (db.UserStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStock", arg0, arg1)
	ret0, _ := ret[0].(db.UserStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserStock indicates an expected call of UpdateUserStock.
func (mr *MockStoreMockRecorder) UpdateUserStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStock", reflect.TypeOf((*MockStore)(nil).UpdateUserStock), arg0, arg1)
}

// UpdateVerifyEmail mocks base method.
func (m *MockStore) UpdateVerifyEmail(arg0 context.Context, arg1 db.UpdateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerifyEmail indicates an expected call of UpdateVerifyEmail.
func (mr *MockStoreMockRecorder) UpdateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerifyEmail", reflect.TypeOf((*MockStore)(nil).UpdateVerifyEmail), arg0, arg1)
}

// VerifyEmailTx mocks base method.
func (m *MockStore) VerifyEmailTx(arg0 context.Context, arg1 db.VerifyEmailTxParams) (db.VerifyEmailTxResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailTx", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmailTxResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailTx indicates an expected call of VerifyEmailTx.
func (mr *MockStoreMockRecorder) VerifyEmailTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailTx", reflect.TypeOf((*MockStore)(nil).VerifyEmailTx), arg0, arg1)
}
