# This is a basic workflow to help you get started with Actions

name: Depoly images to docker hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master", "ft/k8s" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-stockinfo:
    name: Build stockinfo image
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: stockinfo
          IMAGE_TAG: ${{ github.sha }}
          PROJECT_PREFIX: project7-
          PROJECT_NAME: stockinfo
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:$PROJECT_PREFIX$PROJECT_NAME .
          docker push -a $REGISTRY/$REPOSITORY